### PR TITLE
add mem limit for deployments

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
postgres is ok w/ 128mb?

**Comment by gabemontero** [comment]
Its start up costs were really low in my run and examinations with docker
stats, top, /prof examination.  All that said I'm not going to fight it if
you want to bump up.

**Comment by bparees** [comment]
nope, I trust your findings, just wanted to make sure it wasn't a paste error since mysql was 512.

**Comment by gabemontero** [comment]
Ok cool - and yeah you should see the same in the origin db templates-
momgo i believe is 384 fyi

**Pull request merged**
