### PR TITLE
bump django version

### PR DESCRIPTION
**Pull request by PI-Victor**
fixes: https://github.com/openshift/django-ex/issues/38

ps: don't merge just yet, i'm doing a bit of testing out on origin right now.

### CODE REVIEW

**Comment by jfmatth** [comment]
Why not change the django version to reflect a 1.9.x range, so updates will automatically be installed on new builds.  Also, whitenoise 3.x is out, and the configuration is a little different.  Although, I couldn't find 3.x in pip.

**Comment by PI-Victor** [comment]
@jfmatth personally i'm reluctant to let something automatically update itself even minor versions. but you might have something there.
@bparees  @mfojtik what do you guys think?

**Comment by jfmatth** [comment]
Typically, updates to django at that level are mostly security fixes or
urgent bug fixes, but no functionality changes

**Comment by bparees** [comment]
@PI-Victor it sounds safe enough to me i guess.

**Comment by mfojtik** [comment]
@PI-Victor sounds good to me, I'm not fan of "auto-updates" myself when it comes to Docker images :-)

**Comment by PI-Victor** [comment]
i've tested this on origin and it works. can we merge? i don't want to enable automatic updates, i'd rather open a PR once in a while and keep the requirements up to date.

**Comment by bparees** [comment]
@PI-Victor 
1) needs a squash
2) did you test it with a DB to ensure the pageviews count part still works as well?

**Comment by PI-Victor** [comment]
screenshot from 2016-04-29 16-33-02

squashed as promised and it was tested and working

**Pull request merged**
