### PR TITLE
Change welcome page to match other example apps

### PR DESCRIPTION
**Pull request by rhcarvalho**
Matching https://github.com/openshift/rails-ex/pull/21

@bparees @ewolinetz @jhadvig PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by rhcarvalho** [comment]
Screenshot:
image

**Comment by rhcarvalho** [comment]
@mfojtik you were quick... what about the changes in the other repos? I intended to have them reviewed first, since this should match what we (will) have there.

**Comment by mfojtik** [comment]
@rhcarvalho I checked dancer and it looks good there as well ;-)

**Pull request merged**
